  py -m pip install discord
  py -m pip install string
  py -m pip install requests
  py -m pip install datetime
  py -m pip install randoms
  py -m pip install time
  py -m pip install base64
  py -m pip install threading 
  py -m pip install os
  py -m pip install colorama
  py -m pip install json
  py -m pip install discord.ext 
  py -m pip install plyer 
  py -m pip install socket
  py -m pip install webbrowser
  py -m pip install subprocess
  py -m pip install tkinder
  py -m pip install flask
  py -m pip install flask_restful